### PR TITLE
Support for BIGIQ 7.1 

### PR DESCRIPTION
**Pull request by andreykashcheev**
### Summary

New BIGIQ 7.1 introduces a new onboard API and therefore, the role needs to be updated to support the latest BIGIQ version

### Changes

- Starting with BIGIQ7.1, initial onboard is done using new bigiq-setup REST API which available only when device is not launched/licensed. After launching/onboarding) device, the new onboard  REST API endpoint is no longer available. 
- Updated main.yaml to identify BIGIQ version using build field from system/info endpoint
- Added new setup-main_bigiq71.yaml to define new workflow which utilizes new BIGIQ 7.1 REST APIs
- Added new components to support the same onboard workflow as in previous BIGIQ versions (<7.1)

### Additional Information

The new BIGIQ Onboard API works differently, than previous. With new BIGIQ 7.1, there is a new setup endpoint, which can be used for posting all configurations. After we are done with posting all configs, we have to hit Launch endpoint and then monitor the BIGIQ launch. There are a few problems with this: 
     a. It takes a while to finish launch and therefore auth token gets expired
     b. As a part of launch, BIGIQ gets restarted which causes failure on Ansible side. 
The problem is workaround using the following approach: 
       - Request a new token before start monitoring the BIGIQ launch
       - Introduced logic to capture BIGIQ restart:

               1) When restart happens, sleep 2 mins
               2) Calls /system/info to understand when BIGIQ becomes available
               3) Request a new token
               4) Continue to configuring HA pair if needed

### CODE REVIEW

**Comment by nitinthewiz** [comment]
Seeing the changelist, I'm wondering if it's beneficial to create a post-7.1 role separate from this one? The API churn is quite large.

**Comment by nitinthewiz** [comment]
@andreykashcheev can you please fix all the pep8 issues so the sanity tests pass?

**Comment by rjouhann** [comment]
@nitinthewiz I would prefer keeping the same role so user experience is the same whatever BIG-IQ version used. The role can check the BIG-IQ version and use proper API calls.

**Comment by nitinthewiz** [comment]
@rjouhann fair enough. Keeping a consistent experience does make sense.

**Comment by andreykashcheev** [comment]
> @andreykashcheev can you please fix all the pep8 issues so the sanity tests pass?

Sure - I will fix the sanity checks. I will provide an update when it will be done. 

Thanks!

**Comment by andreykashcheev** [comment]
> > @andreykashcheev can you please fix all the pep8 issues so the sanity tests pass?
> 
> Sure - I will fix the sanity checks. I will provide an update when it will be done.
> 
> Thanks!

All lint errors are fixed now.

**Pull request merged**
